package cym.demo.ssmdemo.bean;

import java.math.BigDecimal;

public class TbSource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SOURCE.SID
     *
     * @mbggenerated
     */
    private BigDecimal sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SOURCE.CID
     *
     * @mbggenerated
     */
    private BigDecimal cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_SOURCE.SOURCE
     *
     * @mbggenerated
     */
    private BigDecimal source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SOURCE.SID
     *
     * @return the value of TB_SOURCE.SID
     *
     * @mbggenerated
     */
    public BigDecimal getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SOURCE.SID
     *
     * @param sid the value for TB_SOURCE.SID
     *
     * @mbggenerated
     */
    public void setSid(BigDecimal sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SOURCE.CID
     *
     * @return the value of TB_SOURCE.CID
     *
     * @mbggenerated
     */
    public BigDecimal getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SOURCE.CID
     *
     * @param cid the value for TB_SOURCE.CID
     *
     * @mbggenerated
     */
    public void setCid(BigDecimal cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_SOURCE.SOURCE
     *
     * @return the value of TB_SOURCE.SOURCE
     *
     * @mbggenerated
     */
    public BigDecimal getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_SOURCE.SOURCE
     *
     * @param source the value for TB_SOURCE.SOURCE
     *
     * @mbggenerated
     */
    public void setSource(BigDecimal source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sid=").append(sid);
        sb.append(", cid=").append(cid);
        sb.append(", source=").append(source);
        sb.append("]");
        return sb.toString();
    }
}