package cym.demo.ssmdemo.dao;

import cym.demo.ssmdemo.bean.TbSource;
import cym.demo.ssmdemo.bean.TbSourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbSourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    int countByExample(TbSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    int deleteByExample(TbSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    int insert(TbSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    int insertSelective(TbSource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    List<TbSource> selectByExample(TbSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbSource record, @Param("example") TbSourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_SOURCE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbSource record, @Param("example") TbSourceExample example);
}